name: PR updater

on:
  pull_request:
    branches: [master]

permissions:
  pull-requests: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: actions/checkout@v4

      - name: Update PR
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: gh pr edit ${{ github.event.pull_request.number }} --title "Updated dependencies" --add-assignee ${{ github.repository_owner }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
